### ISSUE TITLE
Very slow loading large Image Files

### ISSUE THREAD

**Issue by mr-gilberto** [mapleqin/PictureChooseLib#2]
Very slow loading large Image Files, and chrashes.

**Comment by devsoulwolf** [comment]
I also found this problem, in the near future will be modified to him, thank you very much for your remind!

**Comment by mapleqin** [comment]
@willby  I also found this problem, in the near future will be modified to him, thank you very much for your remind!

**Comment by tarikyurtlu** [comment]
@devsoulwolf When will you release a new version ? Because I want to use your libs. Thanks.

**Comment by mapleqin** [comment]
@tarikyurtlu Thank you for your support, because I am busy these days, so I will release a new version this weekend, will not only repair some bug, will add something new to improve customizability！
