### ISSUE TITLE
Set custom titles, currently in chinese

### ISSUE THREAD

**Issue by VeeruPV** [mapleqin/PictureChooseLib#3]
Hey there, is there an option to change the titles to custom titles?

**Comment by alirezaafkar** [comment]
Override Chinese strings in your main strings.xml

**Comment by mapleqin** [comment]
Sorry, just did not see your email

You only need to add the following string defined with several of the same name, in different languages, values can be added to the directory in your project /values/strings.xml, and thank you for your support -

```
<string name="ps_picture_choose">选择图片</string>
<string name="ps_picture_choose_count">选择图片(%s)</string>
<string name="ps_gallery_choose">选择相册</string>
<string name="ps_gallery">相册</string>
<string name="ps_cancel">取消</string>
<string name="ps_complete">完成</string>
<string name="ps_select_up_count">最多只能选择%s张图片</string>
<string name="title_activity_gallery_choose">GalleryChooseActivity</string>
<string name="ps_load_image_error">图片加载失败</string>
```
